// Editable artifact metadata.
// Permanent artifacts use type "permanent" and stat values: cache, exec, move, maxIntegrity.
// Temporary artifacts use type "temporary" and effects handled in main.js.
window.arcaneMetadata = window.arcaneMetadata || {};

window.arcaneMetadata.artifacts = [
  {
    id: "powerGlyph",
    name: "Power Glyph",
    type: "permanent",
    rarity: "uncommon",
    image: "artifacts/art_powerglyph.png",
    stat: "exec",
    amount: 1,
    label: "EXECUTIONS +1",
  },
  {
    id: "cacheCore",
    name: "Cache Core",
    type: "permanent",
    rarity: "uncommon",
    image: "artifacts/art_cachecore.png",
    stat: "cache",
    amount: 1,
    label: "CACHE +1",
  },
  {
    id: "integrityLattice",
    name: "Integrity Lattice",
    type: "permanent",
    rarity: "common",
    image: "artifacts/art_integritylattice.png",
    stat: "maxIntegrity",
    amount: 1,
    label: "Max Integrity +1",
  },
  {
    id: "biomechanics",
    name: "Biomechanics",
    type: "permanent",
    rarity: "rare",
    image: "artifacts/art_biomechanics.png",
    stat: "move",
    amount: 1,
    label: "Actions +1",
  },
  {
    id: "adrenalineSpike",
    name: "Adrenaline Spike",
    type: "temporary",
    rarity: "common",
    image: "artifacts/art_adrenalinespike.png",
    label: "Actions +1 for next 3 turns",
    uses: 1,
    effect: {
      type: "temporaryActions",
      amount: 1,
      turns: 3,
    },
  },
  {
    id: "jungleHerbs",
    name: "Jungle Herbs",
    type: "temporary",
    rarity: "uncommon",
    image: "artifacts/art_jungleherbs.png",
    label: "Heal 2 Integrity",
    effect: {
      type: "healIntegrity",
      amount: 2,
    },
  },
  {
    id: "realityWarp",
    name: "Reality Warp",
    type: "temporary",
    rarity: "rare",
    image: "artifacts/art_realitywarp.png",
    label: "1 Use: deal 1 Arcane Damage to all surrounding enemies",
    uses: 1,
    effect: {
      type: "damageAdjacentAll",
      amount: 1,
      damageType: "arcane",
    },
  },
  {
    id: "pixelBomb",
    name: "Pixel Bomb",
    type: "temporary",
    rarity: "common",
    image: "artifacts/art_pixelbomb.png",
    label: "1 Use: deal 2 Physical Damage to an adjacent enemy",
    uses: 1,
    effect: {
      type: "damageAdjacent",
      amount: 2,
      damageType: "physical",
    },
  },
  {
    id: "sigilGlyph",
    name: "Sigil-Glyph",
    type: "temporary",
    rarity: "uncommon",
    label: "Counts as one random sigil during Sigil-Casting",
    uses: 1,
    effect: {
      type: "sigilGlyph",
    },
  },
  {
    id: "psychicResonator",
    name: "Psychic Resonator",
    type: "temporary",
    rarity: "rare",
    image: "artifacts/psychic_resonator.png",
    label: "Reveal all enemies and deal 4 Arcane Damage to one",
    uses: 1,
    effect: {
      type: "revealEnemiesDamage",
      amount: 4,
      damageType: "arcane",
    },
  },
  {
    id: "magShield",
    name: "Mag Shield",
    type: "temporary",
    rarity: "uncommon",
    image: "artifacts/mag_shield.png",
    label: "Shield all damage for 3 turns",
    uses: 1,
    effect: {
      type: "shieldDamage",
      turns: 3,
    },
  },
  {
    id: "skyWalkers",
    name: "Sky Walkers",
    type: "temporary",
    rarity: "common",
    image: "artifacts/Sky_Walkers.png",
    label: "Each Move action goes 1 extra space for 5 turns",
    uses: 1,
    effect: {
      type: "moveActionRangeBonus",
      amount: 1,
      turns: 5,
    },
  },
  {
    id: "arcaneKnowledge",
    name: "Arcane Knowledge",
    type: "permanent",
    rarity: "rare",
    image: "artifacts/arcane_knowledge.png",
    label: "Gain a new 8-sided blank die",
    effect: {
      type: "addBlankDie",
      sides: 8,
    },
  },
  {
    id: "cyclesPip",
    name: "Cycles Pip",
    type: "pip",
    rarity: "uncommon",
    label: "Crafting pip: +10 Cycles when this die side rolls",
    effect: {
      type: "pip",
      pipType: "cycles",
    },
  },
  {
    id: "fortunePip",
    name: "Fortune Pip",
    type: "pip",
    rarity: "uncommon",
    label: "Crafting pip: this die side is 10% more likely to roll",
    effect: {
      type: "pip",
      pipType: "fortune",
    },
  },
  {
    id: "arcanePip",
    name: "Arcane Pip",
    type: "pip",
    rarity: "rare",
    label: "Crafting pip: +1 Execution for this Sigil-Cast when this die side rolls",
    effect: {
      type: "pip",
      pipType: "arcane",
    },
  },
];
