// Editable enemy metadata.
// Add new entries to window.arcaneMetadata.glitchspawn, then reference their ids from room generation in main.js.
window.arcaneMetadata = window.arcaneMetadata || {};

window.arcaneMetadata.glitchspawn = {
  voidRaider: {
    id: "voidRaider",
    name: "Void Raider",
    image: "pixel art/glitchspawn_1_px.png",
    xpValue: 25,
    behavior: "hyperAggressive",
    stats: {
      integrity: 4,
      physicalDefense: 0,
      arcaneDefense: 0,
      power: 1,
      accuracy: 0.4,
    },
  },
  surgeCrawler: {
    id: "surgeCrawler",
    name: "Surge Crawler",
    image: "pixel art/glitchspawn_2_px.png",
    xpValue: 30,
    behavior: "aggressive",
    stats: {
      integrity: 3,
      physicalDefense: 0,
      arcaneDefense: 0,
      power: 2,
      accuracy: 0.45,
    },
  },
  mindPhantom: {
    id: "mindPhantom",
    name: "Vision Phantom",
    image: "pixel art/glitchspawn3_px.png",
    xpValue: 40,
    behavior: "aggressive",
    stats: {
      integrity: 5,
      physicalDefense: 0,
      arcaneDefense: 1,
      power: 1,
      accuracy: 0.4,
    },
  },
  plasmoid: {
    id: "plasmoid",
    name: "Plasmoid",
    image: "characters/glitchspawn_4.png",
    xpValue: 35,
    behavior: "stationary",
    proximityAttack: true,
    stats: {
      integrity: 4,
      physicalDefense: 0,
      arcaneDefense: 0,
      power: 2,
      accuracy: 0.78,
    },
  },
  shadowclaw: {
    id: "shadowclaw",
    name: "Shadowclaw",
    image: "characters/glitchspawn_5.png",
    xpValue: 45,
    behavior: "hyperAggressive",
    stats: {
      integrity: 5,
      physicalDefense: 3,
      arcaneDefense: 0,
      power: 2,
      accuracy: 0.5,
    },
  },
  riftGhoul: {
    id: "riftGhoul",
    name: "Rift Ghoul",
    image: "characters/Rift_Ghoul.png",
    xpValue: 65,
    behavior: "aggressive",
    fixedStats: true,
    stats: {
      integrity: 7,
      physicalDefense: 2,
      arcaneDefense: 2,
      power: 4,
      accuracy: 0.5,
      range: 2,
    },
  },
  skinEater: {
    id: "skinEater",
    name: "Skin-Eater",
    image: "characters/Skineater.png",
    xpValue: 50,
    behavior: "stationary",
    fixedStats: true,
    spawnChance: 0.1,
    spawnType: "skinSpawn",
    stats: {
      integrity: 6,
      physicalDefense: 1,
      arcaneDefense: 0,
      power: 3,
      accuracy: 0.6,
      move: 0,
    },
  },
  skinSpawn: {
    id: "skinSpawn",
    name: "Skin-Spawn",
    image: "characters/skinspawn.png",
    xpValue: 15,
    behavior: "hyperAggressive",
    fixedStats: true,
    stats: {
      integrity: 2,
      physicalDefense: 0,
      arcaneDefense: 0,
      power: 1,
      accuracy: 0.5,
      move: 2,
    },
  },
};
